### ISSUE TITLE
How to deal with disagreement between annotators

### ISSUE THREAD

**Issue by wwfan91** [cnap/ynacc#2]
Hi!
First, I would link to thank authors for creating the nice corpus. I also read your related paper "Automatically Identifying Good Conversations Online (Yes, they do exist!)".

I just download and take a look at it in detail. Since I'm only interested in the 'constructive' label for thread, I observe many threads contain disagreement between annotator. In this situation, how do you decide the final label? is it by majority vote?
Best,

**Comment by cnap** [comment]
Yes, we used majority vote, and when there was no majority, randomly chose a label.
